abbr --add docs "bazelisk build //docs"
abbr --add ga "git add"
abbr --add gcane "git commit --amend --no-edit"
abbr --add gd "git diff"
abbr --add gfo "git fetch origin"
abbr --add gl "git log"
abbr --add grom "git rebase origin/main"
abbr --add gs "git status"
abbr --add n "nvim"
abbr --add serve "bazelisk run //docs:serve"
abbr --add v "vim"
abbr --add wip "git push origin HEAD:refs/for/main%wip"
